### ISSUE TITLE
Stop working on MacOS Catalina 10.15

### ISSUE THREAD

**Issue by nguyennb9** [corpnewt/CPU-Name#2]
I know this version just release and you may need some update to make the script works on Mac OS Catalina 10.15.
I run the script but it doesn't change the CPU name, here is the log

```
########################################################
Setting CPU to AMD Ryzen 5 2600 Six-Core Processor...#
#######################################################
 
Creating backup...

cp: /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/Resources/en.lproj/AppleSystemInfo.strings.bak: Read-only file system
Patching strings for CPU "AMD Ryzen 5 2600 Six-Core Processor            "...
mv: rename /var/folders/lk/b11lxrrs7mv69v4w59txy8440000gn/T/tmphjqIvE/AppleSystemInfo.strings to /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/Resources/en.lproj/AppleSystemInfo.strings: Read-only file system 
Done.
```

**Comment by corpnewt** [comment]
The system is mounted read-only on Catalina by default.  I haven't looked into fixing the script itself for that, and I don't know that I will have time to in the near future.

-CorpNewt

**Comment by nttaivn** [comment]
i disable SIP, and edit SpeedAndTypeFormat and UnknownCPUKind in AppleSystemInfo.strings manually but still cannot change cpu name, i think apple move the cpu name to another key in another file in version 10.15.3

**Comment by grovertb** [comment]
+1

**Comment by juanjsebgarcia** [comment]
I have tried the following - it looks successful, but it isn't:

Reboot into recovery and run the following in Terminal to disable SIP:
```
csrutil disable
reboot
```

Then log in and make system writeable with

`sudo mount -uw /`
(This will reset on restart)

You can then run the script, but it doesn't work at the moment

Finally re-enable SIP in Recovery mode again
```
csrutil enable
reboot
```

This was tested on Catalina 10.15.7
