### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by mikul** [corpnewt/CPU-Name#7]
sh-3.2# python ./CPU-Name/CPU-Name.command
  File "./CPU-Name/CPU-Name.command", line 9
    NL=$'\n'
       ^
SyntaxError: invalid syntax

MacOS 12.1 Beta

**Comment by corpnewt** [comment]
CPU-Name.command is not written in python, it is bash.  If you want to start the script with a specific python interpreter, just point it at the CPU-Name.py script instead.

-CorpNewt
